# -*- coding: utf-8 -*-
"""my_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gv5ewQB1B8CYO8ohVOvYzPZl1jcYbztH
"""

temperature = 50
critical_temp = 100
reactor_on = True

while reactor_on:
  temperature += 5

  if temperature <= 0:
    print('EROR!!!! Reaction reached a criticl temperature!!!!')
    break

  print(f'Temperature of reactor: {temperature}')

  if temperature >= critical_temp:
    print('EROR!!!! Reaction reached a criticl temperature!!!!')
    break

  print('1 - to lower the temperature of reactor')
  print('2 - to rise the temperature of reactor')

  choise = int(input('You will choise: '))
  if choise == 1:
    temperature -= 10
    print(f'Temperature of reactor: {temperature}')
  elif choise == 2:
    temperature += 10
    print(f'Temperature of reactor: {temperature}')

